spring.application.name=piemanager

spring.datasource.url=jdbc:sqlite:piemanager.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

springdoc.swagger-ui.path=/swagger-ui.html

app.jwt.secret=26e80c572bbca85dfa5d29097e9d01d783d70a06f93da49b319413a604763e7f
app.jwt.expiration-ms=3600000
